apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-server
  template:
    metadata:
      labels:
        app: argocd-server
    spec:
      serviceAccountName: argocd-server
      containers:
        - name: argocd-server
          image: argoproj/argocd:v2.0.5
          ports:
            - containerPort: 8080
          env:
            - name: dex.github.clientID
              valueFrom:
                secretKeyRef:
                  name: github-oauth-secret
                  key: clientID
            - name: dex.github.clientSecret
              valueFrom:
                secretKeyRef:
                  name: github-oauth-secret
                  key: clientSecret
          command: ["argocd-server"]