apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: $dex.github.clientID
        clientSecret: $dex.github.clientSecret
        redirectURI: https://your-argocd-server/dex/callback
    oauth2:
      skipApprovalScreen: true
    staticClients:
    - id: argo-cd
      redirectURIs:
      - https://your-argocd-server/auth/callback
      name: Argo CD
      secretEnv: dex-secret