apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/toktechteam/theopskart-devops-projects.git'
    path: DevOps-Projects-Masters/GitOps with Kubernetes/application
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

## To create the application, run the following command, this will default project:
## kubectl apply -f argocd-app.yaml